### ISSUE TITLE
inappropriate int input.

### ISSUE THREAD

**Issue by saminsohag** [mozaddedalfeshani/cpp_hotel_managemet#1]
your input system for int is not appropriate. please correct it.
when i try to input a string to an int type variable it won't shows wrong. and work wired.

add this function at the top of your code.
`
#include <stdio.h>
#include <string.h>
int inputInt(){
   int size = 13;
    char temp[size];
    int i=0;
    notInt:
    // Inputting String.
    fgets(temp,size,stdin);
    
    if(temp[strlen(temp) -1] == '\n'){}else{
        while(getchar()!='\n'){}
    }
    // String inputted successfully
    if(sscanf(temp,"%d",&i)== 0){
	    printf("You have entered: %s\n",temp);
        printf("!Not a number. Try again.\n");
        goto notInt;
    }
    return i;

}
`

replace all of your cin for inputing int type variable

**Comment by mozaddedalfeshani** [comment]
THank's for giving me this information!

**Comment by mozaddedalfeshani** [comment]
@saminsohag Dear I am solved room and phone number entering problem! If you found more problem please notify as soon as possible

**Comment by saminsohag** [comment]
I hope you have solved the input int problem. Then you can close the issue.
